"use client";

import { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Loader2, GitPullRequest, AlertCircle, Lock } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  getUserRepositories,
  createPullRequest,
} from "@/app/generator/github-actions";

interface CreatePRDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  generatedFiles: { [key: string]: string };
  fileNames: { [key: string]: string };
  pattern: string;
  className: string;
}

interface Repository {
  id: number;
  name: string;
  full_name: string;
  default_branch: string;
  private: boolean;
}

export function CreatePRDialog({
  open,
  onOpenChange,
  generatedFiles,
  fileNames,
  pattern,
  className,
}: CreatePRDialogProps) {
  const [repositories, setRepositories] = useState<Repository[]>([]);
  const [selectedRepo, setSelectedRepo] = useState<string>("");
  const [branchName, setBranchName] = useState("");
  const [prTitle, setPrTitle] = useState("");
  const [prDescription, setPrDescription] = useState("");
  const [loading, setLoading] = useState(false);
  const [loadingRepos, setLoadingRepos] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (open) {
      loadRepositories();
      // Set default values
      const defaultBranch = `feature/${pattern.toLowerCase()}-${className.toLowerCase()}-${Date.now()}`;
      setBranchName(defaultBranch);
      setPrTitle(`Add ${pattern} pattern implementation for ${className}`);
      setPrDescription(
        `This PR adds a ${pattern} pattern implementation for the ${className} class.\n\n## Generated Files\n${Object.keys(
          fileNames
        )
          .map((key) => `- ${fileNames[key]}`)
          .join("\n")}\n\nGenerated by Design Patterns Platform.`
      );
    }
  }, [open, pattern, className, fileNames]);

  const loadRepositories = async () => {
    setLoadingRepos(true);
    setError(null);
    try {
      const repos = await getUserRepositories();
      setRepositories(repos);
      if (repos.length === 0) {
        setError(
          "No se encontraron repositorios. Asegúrate de tener repositorios con permisos de escritura."
        );
      }
    } catch (err) {
      const errorMessage =
        err instanceof Error
          ? err.message
          : "Error al cargar los repositorios de GitHub";

      setError(errorMessage);

      // Si el error es de autenticación, agregar sugerencia
      if (
        errorMessage.includes("token") ||
        errorMessage.includes("autenticado")
      ) {
        setError(
          errorMessage +
            " Intenta cerrar sesión y volver a iniciar sesión con GitHub para refrescar los permisos."
        );
      }
    } finally {
      setLoadingRepos(false);
    }
  };

  const handleCreatePR = async () => {
    if (!selectedRepo || !branchName || !prTitle) {
      setError("Por favor completa todos los campos requeridos");
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const files = Object.keys(generatedFiles).map((key) => ({
        path: fileNames[key] || `${key}.cs`,
        content: generatedFiles[key] || "",
      }));

      const result = await createPullRequest({
        repository: selectedRepo,
        branchName,
        prTitle,
        prDescription,
        files,
      });

      if (result.success) {
        // Success! Close dialog and maybe show a success message
        onOpenChange(false);
        // You could add a toast notification here
        if (result.prUrl) {
          window.open(result.prUrl, "_blank");
        }
      } else {
        setError(result.error || "Error al crear el Pull Request");
      }
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Error al crear el Pull Request"
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GitPullRequest className="h-5 w-5" />
            Crear Pull Request en GitHub
          </DialogTitle>
          <DialogDescription>
            Selecciona un repositorio y crea un PR con los archivos generados.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                <div className="space-y-2">
                  <p>{error}</p>
                  {(error.includes("token") ||
                    error.includes("autenticado") ||
                    error.includes("permisos")) && (
                    <div className="mt-2 text-sm">
                      <p className="font-medium">Pasos para resolver:</p>
                      <ol className="list-decimal list-inside space-y-1 mt-1">
                        <li>Cierra sesión en la aplicación</li>
                        <li>Vuelve a iniciar sesión con GitHub</li>
                        <li>
                          Autoriza los permisos solicitados (repo, read:user,
                          user:email)
                        </li>
                        <li>Intenta crear el PR nuevamente</li>
                      </ol>
                    </div>
                  )}
                </div>
              </AlertDescription>
            </Alert>
          )}

          <div className="space-y-2">
            <Label htmlFor="repository">Repositorio *</Label>
            {loadingRepos ? (
              <div className="flex items-center justify-center py-4">
                <Loader2 className="h-6 w-6 animate-spin" />
              </div>
            ) : (
              <Select value={selectedRepo} onValueChange={setSelectedRepo}>
                <SelectTrigger id="repository">
                  <SelectValue placeholder="Selecciona un repositorio" />
                </SelectTrigger>
                <SelectContent>
                  {repositories.length === 0 ? (
                    <SelectItem value="no-repos" disabled>
                      No se encontraron repositorios
                    </SelectItem>
                  ) : (
                    repositories.map((repo) => (
                      <SelectItem key={repo.id} value={repo.full_name}>
                        <div className="flex items-center gap-2">
                          <span>{repo.full_name}</span>
                          {repo.private && (
                            <Lock className="h-3 w-3 text-muted-foreground" />
                          )}
                        </div>
                      </SelectItem>
                    ))
                  )}
                </SelectContent>
              </Select>
            )}
            <p className="text-xs text-muted-foreground">
              Repositorios públicos y privados donde tienes permisos de
              escritura
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="branch">Nombre de la rama *</Label>
            <Input
              id="branch"
              value={branchName}
              onChange={(e) => setBranchName(e.target.value)}
              placeholder="feature/singleton-gamemanager"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="title">Título del PR *</Label>
            <Input
              id="title"
              value={prTitle}
              onChange={(e) => setPrTitle(e.target.value)}
              placeholder="Add Singleton pattern for GameManager"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Descripción</Label>
            <Textarea
              id="description"
              value={prDescription}
              onChange={(e) => setPrDescription(e.target.value)}
              placeholder="Descripción del Pull Request..."
              rows={6}
            />
          </div>

          <div className="rounded-lg bg-muted p-3">
            <p className="text-sm font-medium mb-2">
              Archivos que se incluirán:
            </p>
            <ul className="text-sm text-muted-foreground space-y-1">
              {Object.keys(fileNames).map((key) => (
                <li key={key} className="flex items-center gap-2">
                  <span className="h-1.5 w-1.5 rounded-full bg-primary" />
                  {fileNames[key]}
                </li>
              ))}
            </ul>
          </div>
        </div>

        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={loading}
          >
            Cancelar
          </Button>
          <Button onClick={handleCreatePR} disabled={loading || loadingRepos}>
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Creando PR...
              </>
            ) : (
              <>
                <GitPullRequest className="mr-2 h-4 w-4" />
                Crear Pull Request
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
